export default {
    RECEIVE_MONEY: "RECEIVE_MONEY",
    FOLLOWING_POST: "FOLLOWING_POST",
    RECEIVE_FOLLOWINGS: "RECEIVE_FOLLOWINGS",
    RECEIVE_UNFOLLOWINGS: "RECEIVE_UNFOLLOWINGS",
    RECEIVE_REACTION: "RECEIVE_REACTION",
    RECEIVE_COMMENT: "RECEIVE_COMMENT"
}